### PR TITLE
Normalize quaternions. Closes #60.

### LINKED ISSUE #60: IK solution not found if quaternion not properly normalised
### Commit
83d9f04

### Steps to reproduce
Run a program with
```
    r.move(Ptp(goal=[0,0,0,0,0,0]))

    or1 = orientation=Quaternion(0.145059, -0.035913, -0.657978, 0.738060)
    or2 = orientation=Quaternion(0.145, -0.036, -0.658, 0.738)
    r.move(Ptp(goal=Pose(position=Point(0.054, -0.000, 1.078), orientation=or1), vel_scale=0.1))
    r.move(Ptp(goal=[0,0,0,0,0,0]))
    r.move(Ptp(goal=Pose(position=Point(0.054, -0.000, 1.078), orientation=or2), vel_scale=0.1)) # Will fail

```

Note: x²+y²+z²+w² ist bei or1=0.999999469134 und bei or2=0.999929

### Expected behavior
Both ways should work

### Observed behavior
Using a "not so much" normal quaternion yields in "IK solution not found"

### PR DESCRIPTION
**Pull request by agutenkunst**

### CODE REVIEW

File: pilz_trajectory_generation/include/pilz_trajectory_generation/trajectory_functions.h [hunk 1]
```diff
@@ -240,6 +241,6 @@ bool isStateColliding(const bool test_for_self_collision,
                       const double * const ik_solution);
 }
 
-
+void normalizeQuaterion(geometry_msgs::Quaternion & quat);
```
Comment (martiniil) [inline pilz_trajectory_generation/include/pilz_trajectory_generation/trajectory_functions.h]: Fix typo (query replace): normalizeQuater **n** ion(...)

**Review by martiniil — CHANGES_REQUESTED** [review]
It works! Just a typo

**Review by martiniil — APPROVED** [review]
